version: '3.7'

services:
  learning_cortex-filecontainer:
    image: geircode/learning_cortex-filecontainer:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning_cortex-filecontainer-1
    networks:
      - learning_cortex-filecontainer-network      

networks:
  learning_cortex-filecontainer-network:
    name: learning_cortex-filecontainer-network    
    